[package]
name = "sp-sync"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sp-model = { path = "../sp-model" }
sp-oplog = { path = "../sp-oplog" }
sp-store = { path = "../sp-store" }
ureq = "3.4.1"
flate2 = "1.1.10"
base64 = "0.23.1"
argon2 = "0.6.0"
aes-gcm = "0.11.1"
pbkdf2 = "0.13.0"
sha2 = "0.11.0"
hmac = "0.13.0"
getrandom = "0.4.3"
