// SPDX-License-Identifier: GPL-3.0-or-later
// Generated from upstream action-types.enum.ts + action-type-codes.ts (MIT, (c) 2018 Johannes Millan).
pub const ACTION_CODES: &[(&str, &str)] = &[
    ("[Archive] Compress Archive", "AC"),
    ("[Archive] Flush Young to Old", "AF"),
    ("[Archive] Remote Archive Data Applied", "AR"),
    ("[Boards] Add Board", "BA"),
    ("[Boards] Remove Board", "BD"),
    ("[Boards] Update Board", "BU"),
    ("[Boards] Update Panel Cfg", "BP"),
    ("[Boards] Update Panel Cfg TaskIds", "BT"),
    ("[Boards] Sort Boards", "BS"),
    ("[Global Config] Update Global Config Section", "CU"),
    ("[Metric] Add Metric", "EA"),
    ("[Metric] Delete Metric", "ED"),
    ("[Metric] Update Metric", "EU"),
    ("[Metric] Upsert Metric", "EX"),
    ("[Metric] Log Focus Session", "EL"),
    ("[Tag] Add Tag", "GA"),
    ("[Tag] Update Tag", "GU"),
    ("[Tag] Delete Tag", "GD"),
    ("[Tag] Delete multiple Tags", "GDM"),
    ("[Tag] Update Tag Order", "GO"),
    ("[Tag] Update Advanced Config", "GC"),
    ("[Task Shared] addTask", "HA"),
    ("[Task Shared] updateTask", "HU"),
    ("[Task Shared] deleteTask", "HD"),
    ("[Task Shared] deleteTasks", "HDM"),
    ("[Task Shared] moveToArchive", "HX"),
    ("[Task Shared] restoreTask", "HR"),
    ("[Task Shared] restoreDeletedTask", "HRD"),
    ("[Task Shared] convertToSubTask", "HCS"),
    ("[Task Shared] convertToMainTask", "HC"),
    ("[Task Shared] scheduleTaskWithTime", "HS"),
    ("[Task Shared] reScheduleTaskWithTime", "HSR"),
    ("[Task Shared] unscheduleTask", "HSX"),
    ("[Task Shared] dismissReminderOnly", "HRX"),
    ("[Task Shared] updateTasks", "HUM"),
    ("[Task Shared] moveToOtherProject", "HMP"),
    ("[Task Shared] deleteProject", "HPD"),
    ("[Task Shared] planTasksForToday", "HPT"),
    ("[Task Shared] removeTasksFromTodayTag", "HRT"),
    ("[Task Shared] addTagToTask", "HGT"),
    ("[Task Shared] removeTagsForAllTasks", "HGR"),
    ("[Task Shared] moveTaskInTodayTagList", "HMT"),
    ("[Task Shared] batchUpdateForProject", "HBP"),
    ("[Task Shared] deleteIssueProvider", "HID"),
    ("[Task Shared] deleteIssueProviders", "HIM"),
    ("[Task Shared] deleteTaskRepeatCfg", "HRC"),
    ("[Task Shared] applyShortSyntax", "HSS"),
    ("[Task Shared] setDeadline", "HDL"),
    ("[Task Shared] planDeadlineTasksForToday", "HDT"),
    ("[Task Shared] removeDeadline", "HXD"),
    ("[Task Shared] clearDeadlineReminder", "HCR"),
    ("[IssueProvider/API] Add IssueProvider", "IA"),
    ("[IssueProvider/API] Update IssueProvider", "IU"),
    ("[IssueProvider/API] Sort IssueProviders First", "IS"),
    ("[TimeTracking] Sync sessions", "KS"),
    ("[TimeTracking] Sync time spent", "KT"),
    ("[TimeTracking] Update Work Context Data", "KW"),
    ("[Planner] Upsert Planner Day", "LU"),
    ("[Planner] Transfer Task", "LT"),
    ("[Planner] Move In List", "LM"),
    ("[Planner] Move Before Task", "LB"),
    ("[Planner] Plan Task for Day", "LP"),
    ("[MenuTree] Update Project Tree", "MP"),
    ("[MenuTree] Update Tag Tree", "MG"),
    ("[MenuTree] Update Folder", "MU"),
    ("[MenuTree] Delete Folder", "MD"),
    ("[Note] Add Note", "NA"),
    ("[Note] Update Note", "NU"),
    ("[Note] Delete Note", "ND"),
    ("[Note] Update Note Order", "NO"),
    ("[Note] Move to other project", "NM"),
    ("[Project] Add Project", "PA"),
    ("[Project] Update Project", "PU"),
    ("[Project] Update Project Order", "PO"),
    ("[Project] Update Project Advanced Cfg", "PC"),
    ("[Project] Archive Project", "PX"),
    ("[Project] Unarchive Project", "PR"),
    ("[Project] Complete Project", "PCO"),
    ("[Project] Reopen Project", "PRO"),
    ("[Project] Toggle hide from menu", "PH"),
    ("[Project] Move Task in Backlog", "PM"),
    ("[Project] Move Task Up in Backlog", "PMU"),
    ("[Project] Move Task Down in Backlog", "PMD"),
    ("[Project] Move Task to Top in Backlog", "PMT"),
    ("[Project] Move Task to Bottom in Backlog", "PMB"),
    ("[Project] Move Task from regular to backlog", "PRB"),
    ("[Project] Move Task from backlog to regular", "PBR"),
    ("[Project] Auto Move Task from regular to backlog", "PAB"),
    ("[Project] Auto Move Task from backlog to regular", "PAR"),
    ("[Project] Move all backlog tasks to regular", "PBA"),
    ("[TaskRepeatCfg][Task] Add TaskRepeatCfg to Task", "RA"),
    ("[TaskRepeatCfg] Update TaskRepeatCfg", "RU"),
    ("[TaskRepeatCfg] Update multiple TaskRepeatCfgs", "RUM"),
    ("[TaskRepeatCfg] Delete TaskRepeatCfg", "RD"),
    ("[TaskRepeatCfg] Delete multiple TaskRepeatCfgs", "RDM"),
    ("[TaskRepeatCfg] Delete Single Instance", "RDI"),
    ("[TaskRepeatCfg] Upsert TaskRepeatCfg", "RX"),
    ("[Section] Add Section", "S1"),
    ("[Section] Delete Section", "S2"),
    ("[Section] Update Section", "S3"),
    ("[Section] Update Section Order", "S4"),
    ("[Section] Add Task to Section", "S5"),
    ("[Section] Remove Task from Section", "S6"),
    ("[SimpleCounter] Add SimpleCounter", "SA"),
    ("[SimpleCounter] Update SimpleCounter", "SU"),
    ("[SimpleCounter] Upsert SimpleCounter", "SUS"),
    ("[SimpleCounter] Delete SimpleCounter", "SD"),
    ("[SimpleCounter] Delete multiple SimpleCounters", "SDM"),
    ("[SimpleCounter] Update all SimpleCounters", "SUA"),
    ("[SimpleCounter] Set SimpleCounter Counter Today", "ST"),
    ("[SimpleCounter] Increase SimpleCounter Counter Today", "SI"),
    ("[SimpleCounter] Decrease SimpleCounter Counter Today", "SX"),
    ("[SimpleCounter] Toggle SimpleCounter Counter", "SG"),
    ("[SimpleCounter] Turn off all simple counters", "SO"),
    ("[SimpleCounter] Set SimpleCounter Counter Off", "SF"),
    ("[SimpleCounter] Set SimpleCounter Counter On", "SN"),
    ("[Simple Counter] Set SimpleCounter Counter For Date", "SFD"),
    ("[SimpleCounter] Sync counter time", "SC"),
    ("[SimpleCounter] Update SimpleCounter Order", "SM"),
    ("[Task] Update multiple Tasks (simple)", "TU"),
    ("[Task] Add SubTask", "TA"),
    ("[Task] Move sub task", "TMS"),
    ("[Task] Move up", "TMU"),
    ("[Task] Move down", "TMD"),
    ("[Task] Move to top", "TMT"),
    ("[Task] Move to bottom", "TMB"),
    ("[Task] Remove time spent", "TR"),
    ("[Task] RoundTimeSpentForDay", "TRD"),
    ("[Task] Add new tags from short syntax", "TGS"),
    ("[Task] Update Task Ui", "TUU"),
    ("[Plugin] Upsert User Data", "UU"),
    ("[Plugin] Delete User Data", "UD"),
    ("[Plugin] Upsert Metadata", "UM"),
    ("[Plugin] Delete Metadata", "UDM"),
    ("[WorkContextMeta] Move Task Up in Today", "WMU"),
    ("[WorkContextMeta] Move Task Down in Today", "WMD"),
    ("[WorkContextMeta] Move Task To Top in Today", "WMT"),
    ("[WorkContextMeta] Move Task To Bottom in Today", "WMB"),
    ("[WorkContextMeta] Move Task in Today", "WM"),
    ("[TaskAttachment] Add TaskAttachment", "XA"),
    ("[TaskAttachment] Update TaskAttachment", "XU"),
    ("[TaskAttachment] Delete TaskAttachment", "XD"),
    ("[SP_ALL] Load(import) all data", "YL"),
    ("[SP_ALL] Load(import) backup file", "YB"),
    ("[Migration] Genesis Import", "YM"),
    ("[Recovery] Data Recovery Import", "YR"),
    ("[Repair] Auto Repair", "ZR"),
];
